name: nns
channels:
  - anaconda
dependencies:
  - jupyter
  - numpy
  - pip
  - scipy
  - ipykernel
  - numba
  - pandas
  - pip:
    - scikit-learn
      #- jax[cuda] ## need to use "pip install "jax[cuda11_cudnn82]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html" instead
