name: nns
channels:
  - anaconda
    #- pytorch
    #- defaults
dependencies:
  - jupyter
  - numpy
  - pip
  - scipy
  - ipykernel
    #- pytorch::pytorch
    #- cudatoolkit=10.2
  - numba
    #- pytorch::torchvision
    #- pytorch::torchaudio
    #- pytorch::pytorch-cuda=11.7
